### ISSUE TITLE
icode处理

### ISSUE THREAD

**Issue by coderpak** [mafqla/imooc-admin#2]
你好，这个icode是怎么避开的呢？时不时无效，时不时有效~~~，能不能给一个稳定的方法或者是icode，谢谢了

**Comment by mafqla** [comment]
你可以看一下， request.js的代码。
这个是前端生成的icode， 时不时无效是因为被禁ip了。
要想一直有效的话，请自己去搭一个node.js后台.
或者等我下星期，搭好一个简单的后台。

**Comment by coderpak** [comment]
> 你可以看一下， request.js的代码。 这个是前端生成的icode， 时不时无效是因为被禁ip了。 要想一直有效的话，请自己去搭一个node.js后台. 或者等我下星期，搭好一个简单的后台。

我看到了，太牛了，这是破解了吧，怎么找到这种方法的，佩服！！等你的后台~~~~

**Comment by coderpak** [comment]
请问一直提示icode过期有什么解决方法吗？

**Comment by mafqla** [comment]
更换ip地址

**Comment by mafqla** [comment]
兄弟我快写完后台了，你进qq群，我拉你进我的私人仓库仓库

**Comment by coderpak** [comment]
> 兄弟我快写完后台了，你进qq群，我拉你进我的私人仓库仓库

好的，qq群号码是多少

**Comment by mafqla** [comment]
不用了，我写完了你看下文档，有仓库地址，就剩文章排名的接口没写。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月27日(星期五) 晚上8:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [mafqla/imooc-admin] icode处理 (Issue #2)





  
兄弟我快写完后台了，你进qq群，我拉你进我的私人仓库仓库
  
好的，qq群号码是多少
