### ISSUE TITLE
大佬，请教个问题

### ISSUE THREAD

**Issue by y2kloong** [mafqla/imooc-admin#5]
请问icode是你写那个方法解开了嘛

**Comment by mafqla** [comment]
直接复制那个老师demo破解的，前端没有加密

**Comment by y2kloong** [comment]
> 直接复制那个老师demo破解的，前面没有加密

牛啊，那他其它项目是不是都是这样简单加密了一下

**Comment by mafqla** [comment]
其他项目看不到前端的源码，破解不了啊！还不如自己写一个后台，或者mock一下。他写的这个项目用webpcak部署到服务器，网页端网页端完全可以看到全部代码。

**Comment by y2kloong** [comment]
> 其他项目看不到前端的源码，破解不了啊！还不如自己写一个后台，或者mock一下。他写的这个项目用webpcak部署到服务器，网页端网页端完全可以看到全部代码。

你有这个项目最新到14章的资料视频吗

**Comment by mafqla** [comment]
没有，14章就是讲修复icon，和添加echar的，懒得搞，我只修复了icon的问题

**Comment by y2kloong** [comment]
> icon
好的，谢谢！看了一下你前端学习笔记，学习记录方式真的很好很详细，能分享一下学习方法吗，都看谁的视频资料啥的

**Comment by mafqla** [comment]
codewhy，黑马啊，看得再多都不如看官方文档

**Comment by y2kloong** [comment]
> codewhy，黑马啊，看得再多都不如看官方文档
好的谢谢
